export const VIDEOGAMES_LIST_REQUEST = "VIDEOGAMES_LIST_REQUEST";
export const VIDEOGAMES_LIST_SUCCESS = "VIDEOGAMES_LIST_SUCCESS";
export const VIDEOGAMESS_LIST_FAIL = "VIDEOGAMES_LIST_FAIL";


export const VIDEOGAME_CREATED_REQUEST = "VIDEOGAMES_CREATED_REQUEST";
export const VIDEOGAME_CREATED_SUCCESS = "VIDEOGAMES_CREATED_SUCCESS";
export const VIDEOGAME_CREATED_FAIL = "VIDEOGAMES_CREATED_FAIL";

export const VIDEOGAMES_DETAILS_REQUEST = "VIDEOGAMES_DETAILS_REQUEST";
export const VIDEOGAMES_DETAILS_SUCCESS = "VIDEOGAMES_DETAILS_SUCCESS";
export const VIDEOGAMES_DETAILS_FAIL = "VIDEOGAMES_DETAILS_FAIL";

export const VIDEOGAMES_SEARCH_REQUEST = "VIDEOGAMES_SEARCH_REQUEST";
export const VIDEOGAMES_SEARCH_SUCCESS = "VIDEOGAMES_SEARCH_SUCCESS";
export const VIDEOGAMES_SEARCH_FAIL = "VIDEOGAMES_SEARCH_FAIL";