export const SET_VIDEOGAMES_REQUEST = "SET_VIDEOGAMES_REQUEST";
export const SET_VIDEOGAMES_SUCCESS = "SET_VIDEOGAMES_SUCCESS";
export const SET_VIDEOGAMES_FAIL = "SET_VIDEOGAMES_FAIL";

export const SET_GENRES_REQUEST = "SET_GENRES_REQUEST";
export const SET_GENRES_SUCCESS = "SET_GENRES_SUCCESS";
export const SET_GENRES_FAIL = "SET_GENRES_FAIL";

export const VIDEOGAME_CREATED_REQUEST = "VIDEOGAMES_CREATED_REQUEST";
export const VIDEOGAME_CREATED_SUCCESS = "VIDEOGAMES_CREATED_SUCCESS";
export const VIDEOGAME_CREATED_FAIL = "VIDEOGAMES_CREATED_FAIL";

export const VIDEOGAMES_DETAILS_REQUEST = "VIDEOGAMES_DETAILS_REQUEST";
export const VIDEOGAMES_DETAILS_SUCCESS = "VIDEOGAMES_DETAILS_SUCCESS";
export const VIDEOGAMES_DETAILS_FAIL = "VIDEOGAMES_DETAILS_FAIL";

export const VIDEOGAMES_SEARCH_REQUEST = "VIDEOGAMES_SEARCH_REQUEST";
export const VIDEOGAMES_SEARCH_SUCCESS = "VIDEOGAMES_SEARCH_SUCCESS";
export const VIDEOGAMES_SEARCH_FAIL = "VIDEOGAMES_SEARCH_FAIL";

export const SORT_BY_RATING_ASC = "SORT_BY_RATING_ASC";
export const SORT_BY_RATING_DESC = "SORT_BY_RATING_DESC";

export const SORT_ALPHABETICALLY_ASC = "SORT_ALPHABETICALLY_ASC";
export const SORT_ALPHABETICALLY_DESC = "SORT_ALPHABETICALLY_DESC";

export const FILTER_BY_GENRE = "FILTER_BY_GENRE";

